FROM pytorch/pytorch

RUN apt-get update && apt-get upgrade --yes && apt install --yes --no-install-recommends\
    wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen

RUN pip install wget loguru pydotted ipywidgets && \
    wget https://raw.githubusercontent.com/entmike/disco-diffusion-1/main/downloadModels.py && \
    mkdir models && \
    python downloadModels.py && \
    mv models /models

CMD [ "/bin/bash" ]